### ISSUE TITLE
Makkelijk adres wissen

### ISSUE THREAD

**Issue by bartdegraeve** [digipolisantwerp/location-picker_widget_angular#2]
Je moet eerst heel het bestaande adres selecteren en dan pas kan je het overtypen.
Beter zou zijn: en knop om het adresveld leeg te maken (zoals in Astad)
Deze vraag is ifv de nieuwe meldingstool AMAP

https://jira.antwerpen.be/browse/GIS-51

**Comment by jsebrech** [comment]
De knop zou optioneel moeten zijn (attribuut om te bepalen of de clear knop wel of niet zichtbaar is)

**Comment by Florian-Ramakers** [comment]
De clear knop werd voorzien in versie 4.0 en je kan zelf bepalen of de knop zichtbaar is of niet.
Ik denk dat dit gesloten mag worden?

**Comment by TriangleJuice** [comment]
Closing this issue as it is made an optional feature in v4+
